- name: datatypes demo
  host: local
  connection: local
  vars:
   PROGRAM: "Devops with aws"
   DURETION: 140
   IS_LIVE: true
   DETAILS:
    MONTHS: 4
    TRAINER: "krishna reddy"
   TOPICS:
    - LINUX
    - SHELL
    - ANSIBLE
  tasks:
    - name: print the variables
      ansible.builtin.debug:
       msg: |
          program is: {{ PROGRAM }}
          duretion is: {{ DURETION }}
          is_live?: {{ IS_LIVE }}
          details is: {{ DETAILS }}
          topics is: {{ TOPICS }}
