- name: demo on conditions
  hosts: local
  connection: local
  vars:
   NUMBER_OF_SESSIONS: 7
  tasks:
   - name: is ansible more then 5 sessions
     ansible.builtin.debug:
      msg: "yes, more then 5 session" 
     when: NUMBER_OF_SESSIONS>5   