- name: demo on loop
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: install packages
      ansible.builtin.service:
       name: "{{ name.item }}"
       state: "{{ state.item }}"

      loop:
      - { name: "mysql", state: "present" }
      - { name: "mysql", state: "absent" }
      - { name: "mysql", state: "absent" }
