- name: filters
  hosts: local
  connection: local
  vars:
   topics: linux, ansible, shell, terraform
   tags:
    project: roboshop
    tools: linux
    environment: dev    

  tasks:
   - name: greeting
     ansible.builtin.debug:
      msg: "hai siva kumar, {{ GREETING | default('raju') }}"

   - name: converting string to list
     ansible.builtin.debug:
      msg: "{{ topics | split(',') }}" 

   - name: converting list to srting   
     ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"