- name: filters
  hosts: local
  connection: local
  vars:
   topics: linux, ansible, shell, terraform
   tags:
    project: roboshop
    tools: linux
    environment: dev   
    maplist:{ 
          [
              {
                  "key": "project",
                  "value": "roboshop"
              },
              {
                  "key": "tools",
                  "value": "linux"
              },
              {
                  "key": "environment",
                  "value": "dev"
              }
          ]
        } 
     
   

  tasks:
   - name: greeting
     ansible.builtin.debug:
      msg: "hai siva kumar, {{ GREETING | default('raju') }}"

   - name: converting string to list
     ansible.builtin.debug:
      msg: "{{ topics | split(',') }}" 

   - name: converting list to srting   
     ansible.builtin.debug:
      msg: "{{ tags | dict2items }}"

   - name: converting list to map
     ansible.builtin.debug:
      msg: "{{ maplist | items2dict }}"   